# Generated by Django 2.2.3 on 2019-08-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frst_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
