# Generated by Django 2.2.3 on 2019-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frst_app', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
